--------------------------------------------------------
--  File created - Sunday-March-16-2014   
--------------------------------------------------------
  DROP TABLE "IBSUSER"."IBS_COMPANY" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_COMPANY_BRANCH" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_CONTACT" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_CUSTOMER" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_CUSTOMER_ENQUIRY" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_DOCUMENT_TABLE" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_INSURANCE_COMPANY" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_INSURANCE_COMPANY_CONTACT" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_INSURANCE_COMP_PROD_LINK" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_INSURED_MASTER" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_PRODUCT_MASTER" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_PRODUCT_UW_FIELDS" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_QUOTE_COMPARISION_DETAIL" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_QUOTE_COMPARISION_HEADER" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_QUOTE_SLIP_DETAIL" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_QUOTE_SLIP_HEADER" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_RECORD_TYPES" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_ROLES" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_ROLES_PRODUCT_PRIVILEGES" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_STATUS_MASTER" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_TASK" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_USER" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_USER_PRODUCT_LINK" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_USER_ROLE_LINK" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_UW_TRANSACTION" cascade constraints;
  DROP TABLE "IBSUSER"."IBS_UW_TRANSACTION_HEADER" cascade constraints;
  DROP SEQUENCE "IBSUSER"."IBS_CONTACT_SEQ";
  DROP SEQUENCE "IBSUSER"."IBS_CUSTOMER_SEQ";
  DROP MATERIALIZED VIEW "IBSUSER"."IBS_MAS_LOOKUP";
  DROP VIEW "IBSUSER"."IBS_V_INSURED_SEARCH";
--------------------------------------------------------
--  DDL for Sequence IBS_CONTACT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "IBSUSER"."IBS_CONTACT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 27 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence IBS_CUSTOMER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "IBSUSER"."IBS_CUSTOMER_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 34 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Table IBS_COMPANY
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_COMPANY" 
   (	"CODE" VARCHAR2(10 BYTE), 
	"SHORTNAME" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(10 BYTE), 
	"CONTACT_ID" NUMBER(*,0), 
	"STATUS" VARCHAR2(1 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_COMPANY_BRANCH
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_COMPANY_BRANCH" 
   (	"CODE" VARCHAR2(10 BYTE), 
	"SHORTNAME" VARCHAR2(10 BYTE), 
	"COMPANY_CODE" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"ABBR" VARCHAR2(4 BYTE), 
	"CONTACT_ID" NUMBER(25,0), 
	"STATUS" VARCHAR2(1 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_CONTACT
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_CONTACT" 
   (	"ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"MIDDLE_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(3 BYTE), 
	"PRIMARY_EMAIL_ID" VARCHAR2(50 BYTE), 
	"PRIMARY_MOBILE_NO" VARCHAR2(20 BYTE), 
	"PRIMARY_LANDLINE_NO" VARCHAR2(25 BYTE), 
	"FAXNO" VARCHAR2(25 BYTE), 
	"CITY" VARCHAR2(30 BYTE), 
	"COUNTRY" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"POBOX" VARCHAR2(10 BYTE), 
	"LOCATION_LATTITUDE" NUMBER(5,0), 
	"LOCATION_LONGITUDE" NUMBER(5,0), 
	"ALTERNATE_EMAIL_ID_1" VARCHAR2(50 BYTE), 
	"ALTERNATE_MOBILE_NO_1" VARCHAR2(20 BYTE), 
	"ALTERNATE_LANDLINE_NO_1" VARCHAR2(25 BYTE), 
	"ALTERNATE_EMAIL_ID_2" VARCHAR2(50 BYTE), 
	"ALTERNATE_MOBILE_NO_2" VARCHAR2(20 BYTE), 
	"ALTERNATE_LANDLINE_NO_2" VARCHAR2(25 BYTE), 
	"RECORD_TYPE" NUMBER(2,0), 
	"IS_STATUS_ACTIVE" VARCHAR2(1 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_CUSTOMER
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_CUSTOMER" 
   (	"ID" NUMBER(*,0), 
	"SALUTATION" VARCHAR2(5 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"CATEGORY" VARCHAR2(15 BYTE), 
	"CUST_GROUP" VARCHAR2(50 BYTE), 
	"CLASSIFICATION" VARCHAR2(15 BYTE), 
	"SOURCE" VARCHAR2(15 BYTE), 
	"CONTACT_ID" NUMBER(25,0), 
	"SALES_EXECUTIVE" VARCHAR2(50 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6), 
	"STATUS" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_CUSTOMER_ENQUIRY
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_CUSTOMER_ENQUIRY" 
   (	"ENQUIRY_NO" NUMBER(*,0), 
	"CUSTOMER_ID" NUMBER(*,0), 
	"TYPE" VARCHAR2(15 BYTE), 
	"RECEIVED_DATE" TIMESTAMP (6), 
	"RCVD_FROM_CONTACT_ID" NUMBER(*,0), 
	"PRODUCT_CLASS" NUMBER(*,0), 
	"ENQUIRY_DESCRIPTION" VARCHAR2(500 BYTE), 
	"ENQUIRY_SUBJECTMATTER_EXPERT" VARCHAR2(50 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6), 
	"IS_ACTIVE" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_DOCUMENT_TABLE
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_DOCUMENT_TABLE" 
   (	"ID" NUMBER(*,0), 
	"ENQUIRY_NO" NUMBER(*,0), 
	"ENQUIRY_TYPE" VARCHAR2(20 BYTE), 
	"DOC_SLIP_ID" NUMBER(*,0), 
	"DOC_SLIP_VERSION" NUMBER(*,0), 
	"DOC_RECIEVED_DESC" VARCHAR2(500 BYTE), 
	"DOCUMENT" BLOB, 
	"DOCUMENT_TYPE" VARCHAR2(50 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DOCUMENT") STORE AS (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))
--------------------------------------------------------
--  DDL for Table IBS_INSURANCE_COMPANY
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_INSURANCE_COMPANY" 
   (	"CODE" VARCHAR2(10 BYTE), 
	"SHORTNAME" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(10 BYTE), 
	"CONTACT_ID" NUMBER(25,0), 
	"STATUS" VARCHAR2(1 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_INSURANCE_COMPANY_CONTACT
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_INSURANCE_COMPANY_CONTACT" 
   (	"ID" NUMBER(*,0), 
	"COMPANY_CODE" VARCHAR2(10 BYTE), 
	"COMPANY_NAME" VARCHAR2(50 BYTE), 
	"PRODUCT_CLASS" NUMBER(*,0), 
	"CONTACT_ID" NUMBER(25,0), 
	"STATUS" VARCHAR2(1 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_INSURANCE_COMP_PROD_LINK
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_INSURANCE_COMP_PROD_LINK" 
   (	"ID" NUMBER(*,0), 
	"PRODUCT_CLASS" NUMBER(*,0), 
	"COMPANY_CODE" VARCHAR2(10 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_INSURED_MASTER
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_INSURED_MASTER" 
   (	"ID" NUMBER(*,0), 
	"CUSTOMER_ID" NUMBER(*,0), 
	"SALUTATION" VARCHAR2(5 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"SOURCE" VARCHAR2(15 BYTE), 
	"CONTACT_ID" NUMBER(25,0), 
	"SALES_EXECUTIVE" VARCHAR2(50 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_PRODUCT_MASTER
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_PRODUCT_MASTER" 
   (	"CLASS" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"SHORTNAME" VARCHAR2(15 BYTE), 
	"CATEGORISATION" VARCHAR2(15 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6), 
	"SUBCLASS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_PRODUCT_UW_FIELDS
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_PRODUCT_UW_FIELDS" 
   (	"ID" NUMBER(*,0), 
	"PRODUCT_CLASS" NUMBER(*,0), 
	"SRL_NO" NUMBER(*,0), 
	"FIELD_NAME" VARCHAR2(30 BYTE), 
	"FIELD_TYPE" VARCHAR2(30 BYTE), 
	"IS_MANDATORY" VARCHAR2(1 BYTE), 
	"FIELD_LENGTH" NUMBER(*,0), 
	"STATUS" VARCHAR2(1 BYTE), 
	"SOURCE_OF_DATA" VARCHAR2(25 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_QUOTE_COMPARISION_DETAIL
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_QUOTE_COMPARISION_DETAIL" 
   (	"ID" NUMBER(*,0), 
	"QUOTE_SLIP_ID" NUMBER(*,0), 
	"QUOTE_SLIP_VERSION" NUMBER(*,0), 
	"ENQUIRY_NO" NUMBER(*,0), 
	"ENQUIRY_TYPE" VARCHAR2(15 BYTE), 
	"QUOTED_COMPANY_CODE" VARCHAR2(10 BYTE), 
	"POLICY_START_DATE" TIMESTAMP (6), 
	"POLICY_EXPIRY_DATE" TIMESTAMP (6), 
	"PRODUCT_CLASS" NUMBER(*,0), 
	"PRODUCT_UW_FIELD_ID" NUMBER(*,0), 
	"PRODUCT_UW_FIELD_ANSWER" VARCHAR2(100 BYTE), 
	"QUOTE_NO" VARCHAR2(50 BYTE), 
	"QUOTED_PREMIUM" NUMBER(15,3), 
	"DISCOUNT_PERCENTAGE" NUMBER(*,0), 
	"LOADING_PERCENTAGE" NUMBER(*,0), 
	"TOTAL_PREMIUM" NUMBER(15,3), 
	"COMMISSION_ON_PRM" NUMBER(15,3), 
	"POLICY_NO" VARCHAR2(50 BYTE), 
	"SUM_INSURED" NUMBER(*,0), 
	"POLICY_TERM" NUMBER(20,3), 
	"COVER_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"QUOTE_DATE" TIMESTAMP (6), 
	"QUOTE_APPROVED_BY" VARCHAR2(10 BYTE), 
	"QUOTE_RECOMMENDED" VARCHAR2(1 BYTE), 
	"CLOSING_SLIP_EMAILED" VARCHAR2(1 BYTE), 
	"QUOTE_CONVERTED_TO_POL" VARCHAR2(1 BYTE), 
	"STATUS_CODE" NUMBER(*,0), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_QUOTE_COMPARISION_HEADER
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_QUOTE_COMPARISION_HEADER" 
   (	"ID" NUMBER(*,0), 
	"QUOTE_SLIP_ID" NUMBER(*,0), 
	"QUOTE_SLIP_VERSION" NUMBER(*,0), 
	"ENQUIRY_NO" NUMBER(*,0), 
	"PRODUCT_CLASS" NUMBER(*,0), 
	"SUB_CLASS" VARCHAR2(50 BYTE), 
	"CUSTOMER_ID" NUMBER(*,0), 
	"INSURED_ID" NUMBER(*,0), 
	"INSURED_NAME" VARCHAR2(50 BYTE), 
	"POLICY_START_DATE" TIMESTAMP (6), 
	"POLICY_EXPIRY_DATE" TIMESTAMP (6), 
	"RECOMMENDATION_SUMMARY" VARCHAR2(1000 BYTE), 
	"QUOTE_RECOMMENDED" VARCHAR2(1 BYTE), 
	"STATUS_CODE" NUMBER(*,0), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_QUOTE_SLIP_DETAIL
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_QUOTE_SLIP_DETAIL" 
   (	"ID" NUMBER(*,0), 
	"QUOTE_SLIP_ID" NUMBER(*,0), 
	"ENQUIRY_NO" NUMBER(*,0), 
	"QUOTE_SLIP_VERSION" NUMBER(*,0), 
	"QUOTE_SLIP_DATE" TIMESTAMP (6), 
	"ENQUIRY_COMPANY_CODE" VARCHAR2(10 BYTE), 
	"PRODUCT_CLASS" NUMBER(*,0), 
	"PRODUCT_UW_FIELD_ID" NUMBER(*,0), 
	"PRODUCT_UW_FIELD_ANSWER" VARCHAR2(200 BYTE), 
	"CONTRACT_PERIOD_FROM" TIMESTAMP (6), 
	"CONTRACT_PERIOD_TO" TIMESTAMP (6), 
	"QUOTE_SLIP_EMAILED" VARCHAR2(1 BYTE), 
	"STATUS_CODE" NUMBER(*,0), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_QUOTE_SLIP_HEADER
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_QUOTE_SLIP_HEADER" 
   (	"ID" NUMBER(*,0), 
	"ENQUIRY_NO" NUMBER(*,0), 
	"QUOTE_SLIP_VERSION" NUMBER(*,0), 
	"QUOTE_SLIP_DATE" TIMESTAMP (6), 
	"PRODUCT_CLASS" NUMBER(*,0), 
	"SUB_CLASS" VARCHAR2(50 BYTE), 
	"CUSTOMER_ID" NUMBER(*,0), 
	"INSURED_ID" NUMBER(*,0), 
	"INSURED_NAME" VARCHAR2(50 BYTE), 
	"CONTRACT_PERIOD_FROM" TIMESTAMP (6), 
	"CONTRACT_PERIOD_TO" TIMESTAMP (6), 
	"POLICY_START_DATE" TIMESTAMP (6), 
	"POLICY_EXPIRY_DATE" TIMESTAMP (6), 
	"QUOTE_SLIP_EMAILED" VARCHAR2(1 BYTE), 
	"REMARKS" VARCHAR2(200 BYTE), 
	"STATUS_CODE" NUMBER(*,0), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_RECORD_TYPES
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_RECORD_TYPES" 
   (	"TYPE" NUMBER(2,0), 
	"DESCRIPTION" VARCHAR2(25 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_ROLES
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_ROLES" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_ROLES_PRODUCT_PRIVILEGES
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_ROLES_PRODUCT_PRIVILEGES" 
   (	"ID" NUMBER(*,0), 
	"ROLE_ID" NUMBER(*,0), 
	"ROLE_NAME" VARCHAR2(30 BYTE), 
	"PRODUCT_CLASS" NUMBER(*,0), 
	"PRODUCT_NAME" VARCHAR2(30 BYTE), 
	"FROM_SI_LIMIT" NUMBER(13,3), 
	"TO_SI_LIMIT" NUMBER(13,3), 
	"EMAIL_REQUISITION" VARCHAR2(1 BYTE), 
	"GENERATE_CLOSINGSLIP" VARCHAR2(1 BYTE), 
	"EMAIL_CLOSINGSLIP" VARCHAR2(1 BYTE), 
	"GENERATE_QUOTESLIP" VARCHAR2(1 BYTE), 
	"EMAIL_QUOTESLIP" VARCHAR2(1 BYTE), 
	"FREETEXT1" VARCHAR2(100 BYTE), 
	"FREETEXT2" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"REMARKS" VARCHAR2(50 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_STATUS_MASTER
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_STATUS_MASTER" 
   (	"CODE" NUMBER(*,0), 
	"DESCRIPTION" VARCHAR2(25 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_TASK
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_TASK" 
   (	"ID" NUMBER(*,0), 
	"ENQUIRY_NO" NUMBER(*,0), 
	"DOCUMENT_ID" VARCHAR2(50 BYTE), 
	"REFERRAL_DESC" VARCHAR2(1000 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"ASSIGNOR_USER_ID" NUMBER(10,0), 
	"ASSIGNEE_USER_ID" NUMBER(10,0), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_USER
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_USER" 
   (	"ID" NUMBER(*,0), 
	"LOGIN_NAME" VARCHAR2(10 BYTE), 
	"PASSWORD" VARCHAR2(10 BYTE), 
	"DESCRIPTION" VARCHAR2(45 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"CONTACT_NO" VARCHAR2(20 BYTE), 
	"EMAIL_ID" VARCHAR2(50 BYTE), 
	"BRANCH_CODE" NUMBER(*,0), 
	"FREEZE_FLAG" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_USER_PRODUCT_LINK
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_USER_PRODUCT_LINK" 
   (	"ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0), 
	"PRODUCT_CLASS" NUMBER(*,0), 
	"STATUS" VARCHAR2(1 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_USER_ROLE_LINK
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_USER_ROLE_LINK" 
   (	"ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0), 
	"ROLE_ID" NUMBER(*,0), 
	"STATUS" VARCHAR2(1 BYTE), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_UW_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_UW_TRANSACTION" 
   (	"QUOTE_SLIP_ID" NUMBER(20,0), 
	"ENQUIRY_NO" NUMBER(20,0), 
	"QUOTE_SLIP_VERSION" NUMBER(3,0), 
	"QUOTE_SLIP_DATE" TIMESTAMP (6), 
	"ENQUIRY_COMPANY_CODE" VARCHAR2(10 BYTE), 
	"PRODUCT_CLASS" NUMBER(10,0), 
	"PRODUCT_UW_FIELD_ID" NUMBER(3,0), 
	"PRODUCT_UW_FIELD_ANSWER" VARCHAR2(200 BYTE), 
	"CONTRACT_PERIOD_FROM" TIMESTAMP (6), 
	"CONTRACT_PERIOD_TO" TIMESTAMP (6), 
	"TYPE" VARCHAR2(15 BYTE), 
	"POLICY_NO" VARCHAR2(50 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table IBS_UW_TRANSACTION_HEADER
--------------------------------------------------------

  CREATE TABLE "IBSUSER"."IBS_UW_TRANSACTION_HEADER" 
   (	"ID" NUMBER(*,0), 
	"POLICY_VERSION" NUMBER(*,0), 
	"QUOTE_ID" NUMBER(*,0), 
	"QUOTE_SLIP_ID" NUMBER(*,0), 
	"QUOTE_SLIP_VERSION" NUMBER(*,0), 
	"ENQUIRY_NO" NUMBER(*,0), 
	"PRODUCT_CLASS" NUMBER(*,0), 
	"SUB_CLASS" VARCHAR2(50 BYTE), 
	"CUSTOMER_ID" NUMBER(*,0), 
	"INSURED_ID" NUMBER(*,0), 
	"INSURED_NAME" VARCHAR2(50 BYTE), 
	"POLICY_START_DATE" TIMESTAMP (6), 
	"POLICY_EXPIRY_DATE" TIMESTAMP (6), 
	"STATUS_CODE" NUMBER(*,0), 
	"REC_CRE_USER_ID" NUMBER(*,0), 
	"REC_CRE_DATE" TIMESTAMP (6), 
	"REC_UPD_USER_ID" NUMBER(*,0), 
	"REC_UPD_DATE" TIMESTAMP (6), 
	"POLICY_NO" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" 
 

   COMMENT ON COLUMN "IBSUSER"."IBS_UW_TRANSACTION_HEADER"."POLICY_NO" IS 'recieved from insurance company'

---------------------------------------------------
--   DATA FOR TABLE IBS_COMPANY
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_COMPANY

---------------------------------------------------
--   END DATA FOR TABLE IBS_COMPANY
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_COMPANY_BRANCH
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_COMPANY_BRANCH

---------------------------------------------------
--   END DATA FOR TABLE IBS_COMPANY_BRANCH
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_CONTACT
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_CONTACT
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (1,'FIRST','mIDDLE','LAST',null,'ABC_GMAIL.COM','9980808080',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'Y',null,null,null,null);
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (9,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (11,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (12,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (13,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (14,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (18,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (19,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (20,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (22,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (23,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (24,null,null,null,null,'customer_save@ibs.com','888888888',null,null,null,null,null,null,1,1,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (25,null,null,null,null,'customer_save@ibs.com','888888888',null,null,null,null,null,null,1,1,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CONTACT (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,PRIMARY_EMAIL_ID,PRIMARY_MOBILE_NO,PRIMARY_LANDLINE_NO,FAXNO,CITY,COUNTRY,ADDRESS,POBOX,LOCATION_LATTITUDE,LOCATION_LONGITUDE,ALTERNATE_EMAIL_ID_1,ALTERNATE_MOBILE_NO_1,ALTERNATE_LANDLINE_NO_1,ALTERNATE_EMAIL_ID_2,ALTERNATE_MOBILE_NO_2,ALTERNATE_LANDLINE_NO_2,RECORD_TYPE,IS_STATUS_ACTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (26,null,null,null,null,'customer_save@ibs.com','888888888',null,null,null,null,null,null,1,1,null,null,null,null,null,null,null,null,null,null,null,null);

---------------------------------------------------
--   END DATA FOR TABLE IBS_CONTACT
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_CUSTOMER
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_CUSTOMER
Insert into IBSUSER.IBS_CUSTOMER (ID,SALUTATION,NAME,CATEGORY,CUST_GROUP,CLASSIFICATION,SOURCE,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,STATUS) values (1,'Mr','Shaik','Retail',null,null,null,1,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CUSTOMER (ID,SALUTATION,NAME,CATEGORY,CUST_GROUP,CLASSIFICATION,SOURCE,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,STATUS) values (11,'Mr','cumstomer save','Retail',null,null,'source',null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CUSTOMER (ID,SALUTATION,NAME,CATEGORY,CUST_GROUP,CLASSIFICATION,SOURCE,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,STATUS) values (12,'Mr','cumstomer save','Retail',null,null,'source',null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CUSTOMER (ID,SALUTATION,NAME,CATEGORY,CUST_GROUP,CLASSIFICATION,SOURCE,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,STATUS) values (13,'Mr','cumstomer save','Retail',null,null,'source',null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CUSTOMER (ID,SALUTATION,NAME,CATEGORY,CUST_GROUP,CLASSIFICATION,SOURCE,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,STATUS) values (14,'Mr','cumstomer save','Retail',null,null,'source',null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CUSTOMER (ID,SALUTATION,NAME,CATEGORY,CUST_GROUP,CLASSIFICATION,SOURCE,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,STATUS) values (25,'Mr','cumstomer save','Retail',null,null,'source',18,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CUSTOMER (ID,SALUTATION,NAME,CATEGORY,CUST_GROUP,CLASSIFICATION,SOURCE,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,STATUS) values (27,'Mr','cumstomer save','Retail',null,null,'source',20,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CUSTOMER (ID,SALUTATION,NAME,CATEGORY,CUST_GROUP,CLASSIFICATION,SOURCE,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,STATUS) values (29,'Mr','cumstomer save','Retail',null,null,'source',22,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CUSTOMER (ID,SALUTATION,NAME,CATEGORY,CUST_GROUP,CLASSIFICATION,SOURCE,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,STATUS) values (30,'Mr','cumstomer save','Retail',null,null,'source',23,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CUSTOMER (ID,SALUTATION,NAME,CATEGORY,CUST_GROUP,CLASSIFICATION,SOURCE,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,STATUS) values (31,'Mr','cumstomer save','Retail',null,null,'source',null,null,null,to_timestamp('16-MAR-14 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,to_timestamp('16-MAR-14 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),1);
Insert into IBSUSER.IBS_CUSTOMER (ID,SALUTATION,NAME,CATEGORY,CUST_GROUP,CLASSIFICATION,SOURCE,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,STATUS) values (32,'Mr','cumstomer save','Retail',null,null,'source',null,null,null,to_timestamp('17-MAR-14 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,to_timestamp('17-MAR-14 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),1);
Insert into IBSUSER.IBS_CUSTOMER (ID,SALUTATION,NAME,CATEGORY,CUST_GROUP,CLASSIFICATION,SOURCE,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,STATUS) values (33,'Mr','cumstomer save','Retail',null,null,'source',26,null,null,to_timestamp('17-MAR-14 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,to_timestamp('17-MAR-14 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),1);

---------------------------------------------------
--   END DATA FOR TABLE IBS_CUSTOMER
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_CUSTOMER_ENQUIRY
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_CUSTOMER_ENQUIRY
Insert into IBSUSER.IBS_CUSTOMER_ENQUIRY (ENQUIRY_NO,CUSTOMER_ID,TYPE,RECEIVED_DATE,RCVD_FROM_CONTACT_ID,PRODUCT_CLASS,ENQUIRY_DESCRIPTION,ENQUIRY_SUBJECTMATTER_EXPERT,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,IS_ACTIVE) values (1,1,'1',null,1,1,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CUSTOMER_ENQUIRY (ENQUIRY_NO,CUSTOMER_ID,TYPE,RECEIVED_DATE,RCVD_FROM_CONTACT_ID,PRODUCT_CLASS,ENQUIRY_DESCRIPTION,ENQUIRY_SUBJECTMATTER_EXPERT,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,IS_ACTIVE) values (2,1,'1',null,1,2,null,null,null,null,null,null,null);
Insert into IBSUSER.IBS_CUSTOMER_ENQUIRY (ENQUIRY_NO,CUSTOMER_ID,TYPE,RECEIVED_DATE,RCVD_FROM_CONTACT_ID,PRODUCT_CLASS,ENQUIRY_DESCRIPTION,ENQUIRY_SUBJECTMATTER_EXPERT,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,IS_ACTIVE) values (3,1,'1',null,1,3,null,null,null,null,null,null,null);

---------------------------------------------------
--   END DATA FOR TABLE IBS_CUSTOMER_ENQUIRY
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_DOCUMENT_TABLE
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_DOCUMENT_TABLE

---------------------------------------------------
--   END DATA FOR TABLE IBS_DOCUMENT_TABLE
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_INSURANCE_COMPANY
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_INSURANCE_COMPANY

---------------------------------------------------
--   END DATA FOR TABLE IBS_INSURANCE_COMPANY
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_INSURANCE_COMPANY_CONTACT
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_INSURANCE_COMPANY_CONTACT

---------------------------------------------------
--   END DATA FOR TABLE IBS_INSURANCE_COMPANY_CONTACT
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_INSURANCE_COMP_PROD_LINK
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_INSURANCE_COMP_PROD_LINK

---------------------------------------------------
--   END DATA FOR TABLE IBS_INSURANCE_COMP_PROD_LINK
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_INSURED_MASTER
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_INSURED_MASTER
Insert into IBSUSER.IBS_INSURED_MASTER (ID,CUSTOMER_ID,SALUTATION,NAME,SOURCE,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (1,1,null,'insured',null,null,null,null,null,null,null);

---------------------------------------------------
--   END DATA FOR TABLE IBS_INSURED_MASTER
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_PRODUCT_MASTER
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_PRODUCT_MASTER
Insert into IBSUSER.IBS_PRODUCT_MASTER (CLASS,NAME,SHORTNAME,CATEGORISATION,STATUS,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,SUBCLASS) values (1,'Life INsurance','LI',null,'1',null,null,null,null,null);
Insert into IBSUSER.IBS_PRODUCT_MASTER (CLASS,NAME,SHORTNAME,CATEGORISATION,STATUS,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,SUBCLASS) values (2,'Vehicle insurance','VI',null,'1',null,null,null,null,null);
Insert into IBSUSER.IBS_PRODUCT_MASTER (CLASS,NAME,SHORTNAME,CATEGORISATION,STATUS,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,SUBCLASS) values (3,'Property Insurance','PI',null,'1',null,null,null,null,null);

---------------------------------------------------
--   END DATA FOR TABLE IBS_PRODUCT_MASTER
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_PRODUCT_UW_FIELDS
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_PRODUCT_UW_FIELDS

---------------------------------------------------
--   END DATA FOR TABLE IBS_PRODUCT_UW_FIELDS
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_QUOTE_COMPARISION_DETAIL
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_QUOTE_COMPARISION_DETAIL
Insert into IBSUSER.IBS_QUOTE_COMPARISION_DETAIL (ID,QUOTE_SLIP_ID,QUOTE_SLIP_VERSION,ENQUIRY_NO,ENQUIRY_TYPE,QUOTED_COMPANY_CODE,POLICY_START_DATE,POLICY_EXPIRY_DATE,PRODUCT_CLASS,PRODUCT_UW_FIELD_ID,PRODUCT_UW_FIELD_ANSWER,QUOTE_NO,QUOTED_PREMIUM,DISCOUNT_PERCENTAGE,LOADING_PERCENTAGE,TOTAL_PREMIUM,COMMISSION_ON_PRM,POLICY_NO,SUM_INSURED,POLICY_TERM,COVER_DESCRIPTION,QUOTE_DATE,QUOTE_APPROVED_BY,QUOTE_RECOMMENDED,CLOSING_SLIP_EMAILED,QUOTE_CONVERTED_TO_POL,STATUS_CODE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (1,2,1,3,'1',null,null,null,null,null,null,null,null,null,null,null,null,'123456',null,null,null,null,null,null,null,null,null,null,null,null,null);

---------------------------------------------------
--   END DATA FOR TABLE IBS_QUOTE_COMPARISION_DETAIL
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_QUOTE_COMPARISION_HEADER
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_QUOTE_COMPARISION_HEADER
Insert into IBSUSER.IBS_QUOTE_COMPARISION_HEADER (ID,QUOTE_SLIP_ID,QUOTE_SLIP_VERSION,ENQUIRY_NO,PRODUCT_CLASS,SUB_CLASS,CUSTOMER_ID,INSURED_ID,INSURED_NAME,POLICY_START_DATE,POLICY_EXPIRY_DATE,RECOMMENDATION_SUMMARY,QUOTE_RECOMMENDED,STATUS_CODE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (1,2,1,3,3,'1',1,1,null,null,null,null,'Y',1,null,null,null,null);

---------------------------------------------------
--   END DATA FOR TABLE IBS_QUOTE_COMPARISION_HEADER
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_QUOTE_SLIP_DETAIL
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_QUOTE_SLIP_DETAIL
Insert into IBSUSER.IBS_QUOTE_SLIP_DETAIL (ID,QUOTE_SLIP_ID,ENQUIRY_NO,QUOTE_SLIP_VERSION,QUOTE_SLIP_DATE,ENQUIRY_COMPANY_CODE,PRODUCT_CLASS,PRODUCT_UW_FIELD_ID,PRODUCT_UW_FIELD_ANSWER,CONTRACT_PERIOD_FROM,CONTRACT_PERIOD_TO,QUOTE_SLIP_EMAILED,STATUS_CODE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (1,2,3,1,null,null,3,null,null,null,null,null,1,null,null,null,null);

---------------------------------------------------
--   END DATA FOR TABLE IBS_QUOTE_SLIP_DETAIL
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_QUOTE_SLIP_HEADER
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_QUOTE_SLIP_HEADER
Insert into IBSUSER.IBS_QUOTE_SLIP_HEADER (ID,ENQUIRY_NO,QUOTE_SLIP_VERSION,QUOTE_SLIP_DATE,PRODUCT_CLASS,SUB_CLASS,CUSTOMER_ID,INSURED_ID,INSURED_NAME,CONTRACT_PERIOD_FROM,CONTRACT_PERIOD_TO,POLICY_START_DATE,POLICY_EXPIRY_DATE,QUOTE_SLIP_EMAILED,REMARKS,STATUS_CODE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (1,2,1,null,2,'1',1,1,null,null,null,null,null,null,null,1,null,null,null,null);
Insert into IBSUSER.IBS_QUOTE_SLIP_HEADER (ID,ENQUIRY_NO,QUOTE_SLIP_VERSION,QUOTE_SLIP_DATE,PRODUCT_CLASS,SUB_CLASS,CUSTOMER_ID,INSURED_ID,INSURED_NAME,CONTRACT_PERIOD_FROM,CONTRACT_PERIOD_TO,POLICY_START_DATE,POLICY_EXPIRY_DATE,QUOTE_SLIP_EMAILED,REMARKS,STATUS_CODE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (2,3,1,null,3,'1',1,1,null,null,null,null,null,null,null,1,null,null,null,null);

---------------------------------------------------
--   END DATA FOR TABLE IBS_QUOTE_SLIP_HEADER
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_RECORD_TYPES
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_RECORD_TYPES
Insert into IBSUSER.IBS_RECORD_TYPES (TYPE,DESCRIPTION) values (1,'Policy');
Insert into IBSUSER.IBS_RECORD_TYPES (TYPE,DESCRIPTION) values (2,'Endorsement');
Insert into IBSUSER.IBS_RECORD_TYPES (TYPE,DESCRIPTION) values (1,'User Contact');
Insert into IBSUSER.IBS_RECORD_TYPES (TYPE,DESCRIPTION) values (2,'Customer Contact');
Insert into IBSUSER.IBS_RECORD_TYPES (TYPE,DESCRIPTION) values (3,'Company Contact');
Insert into IBSUSER.IBS_RECORD_TYPES (TYPE,DESCRIPTION) values (4,'Insurance Company Contact');
Insert into IBSUSER.IBS_RECORD_TYPES (TYPE,DESCRIPTION) values (5,'Company Branch Contact');
Insert into IBSUSER.IBS_RECORD_TYPES (TYPE,DESCRIPTION) values (6,' Portfolio Contact');
Insert into IBSUSER.IBS_RECORD_TYPES (TYPE,DESCRIPTION) values (7,'Insured Contact');

---------------------------------------------------
--   END DATA FOR TABLE IBS_RECORD_TYPES
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_ROLES
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_ROLES

---------------------------------------------------
--   END DATA FOR TABLE IBS_ROLES
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_ROLES_PRODUCT_PRIVILEGES
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_ROLES_PRODUCT_PRIVILEGES

---------------------------------------------------
--   END DATA FOR TABLE IBS_ROLES_PRODUCT_PRIVILEGES
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_STATUS_MASTER
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_STATUS_MASTER
Insert into IBSUSER.IBS_STATUS_MASTER (CODE,DESCRIPTION) values (1,'Active');
Insert into IBSUSER.IBS_STATUS_MASTER (CODE,DESCRIPTION) values (2,'In-active');

---------------------------------------------------
--   END DATA FOR TABLE IBS_STATUS_MASTER
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_TASK
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_TASK

---------------------------------------------------
--   END DATA FOR TABLE IBS_TASK
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_USER
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_USER

---------------------------------------------------
--   END DATA FOR TABLE IBS_USER
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_USER_PRODUCT_LINK
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_USER_PRODUCT_LINK

---------------------------------------------------
--   END DATA FOR TABLE IBS_USER_PRODUCT_LINK
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_USER_ROLE_LINK
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_USER_ROLE_LINK

---------------------------------------------------
--   END DATA FOR TABLE IBS_USER_ROLE_LINK
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_UW_TRANSACTION
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_UW_TRANSACTION

---------------------------------------------------
--   END DATA FOR TABLE IBS_UW_TRANSACTION
---------------------------------------------------


---------------------------------------------------
--   DATA FOR TABLE IBS_UW_TRANSACTION_HEADER
--   FILTER = none used
---------------------------------------------------
REM INSERTING into IBSUSER.IBS_UW_TRANSACTION_HEADER
Insert into IBSUSER.IBS_UW_TRANSACTION_HEADER (ID,POLICY_VERSION,QUOTE_ID,QUOTE_SLIP_ID,QUOTE_SLIP_VERSION,ENQUIRY_NO,PRODUCT_CLASS,SUB_CLASS,CUSTOMER_ID,INSURED_ID,INSURED_NAME,POLICY_START_DATE,POLICY_EXPIRY_DATE,STATUS_CODE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE,POLICY_NO) values (1,1,1,2,1,3,1,'1',1,1,null,null,null,1,null,null,null,null,'1234567890');

---------------------------------------------------
--   END DATA FOR TABLE IBS_UW_TRANSACTION_HEADER
---------------------------------------------------

--------------------------------------------------------
--  Constraints for Table IBS_TASK
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_TASK" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_COMPANY
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_COMPANY" ADD PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_INSURANCE_COMPANY_CONTACT
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_INSURANCE_COMPANY_CONTACT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_STATUS_MASTER
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_STATUS_MASTER" ADD PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_QUOTE_COMPARISION_DETAIL
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_QUOTE_COMPARISION_DETAIL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_COMPANY_BRANCH
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_COMPANY_BRANCH" ADD PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_ROLES
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_ROLES" MODIFY ("NAME" NOT NULL ENABLE)
 
  ALTER TABLE "IBSUSER"."IBS_ROLES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_ROLES" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_QUOTE_SLIP_DETAIL
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_QUOTE_SLIP_DETAIL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_USER_PRODUCT_LINK
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_USER_PRODUCT_LINK" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_ROLES_PRODUCT_PRIVILEGES
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_ROLES_PRODUCT_PRIVILEGES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_PRODUCT_UW_FIELDS
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_PRODUCT_UW_FIELDS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_QUOTE_COMPARISION_HEADER
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_QUOTE_COMPARISION_HEADER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_UW_TRANSACTION_HEADER
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_UW_TRANSACTION_HEADER" ADD PRIMARY KEY ("ID", "POLICY_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_UW_TRANSACTION_HEADER" MODIFY ("POLICY_NO" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table IBS_USER_ROLE_LINK
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_USER_ROLE_LINK" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_CUSTOMER_ENQUIRY
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_CUSTOMER_ENQUIRY" ADD PRIMARY KEY ("ENQUIRY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_PRODUCT_MASTER
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_PRODUCT_MASTER" ADD PRIMARY KEY ("CLASS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_CONTACT
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_CONTACT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_DOCUMENT_TABLE
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_DOCUMENT_TABLE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_QUOTE_SLIP_HEADER
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_QUOTE_SLIP_HEADER" ADD PRIMARY KEY ("ID", "QUOTE_SLIP_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE

--------------------------------------------------------
--  Constraints for Table IBS_INSURANCE_COMP_PROD_LINK
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_INSURANCE_COMP_PROD_LINK" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_INSURED_MASTER
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_INSURED_MASTER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE

--------------------------------------------------------
--  Constraints for Table IBS_CUSTOMER
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_CUSTOMER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_USER
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_USER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table IBS_INSURANCE_COMPANY
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_INSURANCE_COMPANY" ADD PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table IBS_COMPANY
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_COMPANY" ADD FOREIGN KEY ("CONTACT_ID")
	  REFERENCES "IBSUSER"."IBS_CONTACT" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table IBS_COMPANY_BRANCH
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_COMPANY_BRANCH" ADD FOREIGN KEY ("COMPANY_CODE")
	  REFERENCES "IBSUSER"."IBS_COMPANY" ("CODE") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_COMPANY_BRANCH" ADD FOREIGN KEY ("CONTACT_ID")
	  REFERENCES "IBSUSER"."IBS_CONTACT" ("ID") ENABLE

--------------------------------------------------------
--  Ref Constraints for Table IBS_CUSTOMER
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_CUSTOMER" ADD FOREIGN KEY ("CONTACT_ID")
	  REFERENCES "IBSUSER"."IBS_CONTACT" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table IBS_CUSTOMER_ENQUIRY
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_CUSTOMER_ENQUIRY" ADD FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "IBSUSER"."IBS_CUSTOMER" ("ID") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_CUSTOMER_ENQUIRY" ADD FOREIGN KEY ("RCVD_FROM_CONTACT_ID")
	  REFERENCES "IBSUSER"."IBS_CONTACT" ("ID") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_CUSTOMER_ENQUIRY" ADD FOREIGN KEY ("PRODUCT_CLASS")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_MASTER" ("CLASS") ENABLE

--------------------------------------------------------
--  Ref Constraints for Table IBS_INSURANCE_COMPANY
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_INSURANCE_COMPANY" ADD FOREIGN KEY ("CONTACT_ID")
	  REFERENCES "IBSUSER"."IBS_CONTACT" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table IBS_INSURANCE_COMPANY_CONTACT
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_INSURANCE_COMPANY_CONTACT" ADD FOREIGN KEY ("COMPANY_CODE")
	  REFERENCES "IBSUSER"."IBS_COMPANY" ("CODE") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_INSURANCE_COMPANY_CONTACT" ADD FOREIGN KEY ("PRODUCT_CLASS")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_MASTER" ("CLASS") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_INSURANCE_COMPANY_CONTACT" ADD FOREIGN KEY ("CONTACT_ID")
	  REFERENCES "IBSUSER"."IBS_CONTACT" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table IBS_INSURANCE_COMP_PROD_LINK
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_INSURANCE_COMP_PROD_LINK" ADD FOREIGN KEY ("PRODUCT_CLASS")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_MASTER" ("CLASS") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table IBS_INSURED_MASTER
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_INSURED_MASTER" ADD FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "IBSUSER"."IBS_CUSTOMER" ("ID") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_INSURED_MASTER" ADD FOREIGN KEY ("CONTACT_ID")
	  REFERENCES "IBSUSER"."IBS_CONTACT" ("ID") ENABLE

--------------------------------------------------------
--  Ref Constraints for Table IBS_PRODUCT_UW_FIELDS
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_PRODUCT_UW_FIELDS" ADD FOREIGN KEY ("PRODUCT_CLASS")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_MASTER" ("CLASS") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table IBS_QUOTE_COMPARISION_DETAIL
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_QUOTE_COMPARISION_DETAIL" ADD FOREIGN KEY ("QUOTE_SLIP_ID", "QUOTE_SLIP_VERSION")
	  REFERENCES "IBSUSER"."IBS_QUOTE_SLIP_HEADER" ("ID", "QUOTE_SLIP_VERSION") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_QUOTE_COMPARISION_DETAIL" ADD FOREIGN KEY ("PRODUCT_CLASS")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_MASTER" ("CLASS") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_QUOTE_COMPARISION_DETAIL" ADD FOREIGN KEY ("PRODUCT_UW_FIELD_ID")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_UW_FIELDS" ("ID") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_QUOTE_COMPARISION_DETAIL" ADD FOREIGN KEY ("STATUS_CODE")
	  REFERENCES "IBSUSER"."IBS_STATUS_MASTER" ("CODE") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table IBS_QUOTE_COMPARISION_HEADER
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_QUOTE_COMPARISION_HEADER" ADD FOREIGN KEY ("QUOTE_SLIP_ID", "QUOTE_SLIP_VERSION")
	  REFERENCES "IBSUSER"."IBS_QUOTE_SLIP_HEADER" ("ID", "QUOTE_SLIP_VERSION") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_QUOTE_COMPARISION_HEADER" ADD FOREIGN KEY ("PRODUCT_CLASS")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_MASTER" ("CLASS") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_QUOTE_COMPARISION_HEADER" ADD FOREIGN KEY ("STATUS_CODE")
	  REFERENCES "IBSUSER"."IBS_STATUS_MASTER" ("CODE") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table IBS_QUOTE_SLIP_DETAIL
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_QUOTE_SLIP_DETAIL" ADD FOREIGN KEY ("QUOTE_SLIP_ID", "QUOTE_SLIP_VERSION")
	  REFERENCES "IBSUSER"."IBS_QUOTE_SLIP_HEADER" ("ID", "QUOTE_SLIP_VERSION") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_QUOTE_SLIP_DETAIL" ADD FOREIGN KEY ("PRODUCT_CLASS")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_MASTER" ("CLASS") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_QUOTE_SLIP_DETAIL" ADD FOREIGN KEY ("PRODUCT_UW_FIELD_ID")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_UW_FIELDS" ("ID") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_QUOTE_SLIP_DETAIL" ADD FOREIGN KEY ("STATUS_CODE")
	  REFERENCES "IBSUSER"."IBS_STATUS_MASTER" ("CODE") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table IBS_QUOTE_SLIP_HEADER
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_QUOTE_SLIP_HEADER" ADD FOREIGN KEY ("PRODUCT_CLASS")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_MASTER" ("CLASS") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_QUOTE_SLIP_HEADER" ADD FOREIGN KEY ("STATUS_CODE")
	  REFERENCES "IBSUSER"."IBS_STATUS_MASTER" ("CODE") ENABLE


--------------------------------------------------------
--  Ref Constraints for Table IBS_ROLES_PRODUCT_PRIVILEGES
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_ROLES_PRODUCT_PRIVILEGES" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "IBSUSER"."IBS_ROLES" ("ID") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_ROLES_PRODUCT_PRIVILEGES" ADD FOREIGN KEY ("ROLE_NAME")
	  REFERENCES "IBSUSER"."IBS_ROLES" ("NAME") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_ROLES_PRODUCT_PRIVILEGES" ADD FOREIGN KEY ("PRODUCT_CLASS")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_MASTER" ("CLASS") ENABLE

--------------------------------------------------------
--  Ref Constraints for Table IBS_TASK
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_TASK" ADD FOREIGN KEY ("STATUS_CODE")
	  REFERENCES "IBSUSER"."IBS_STATUS_MASTER" ("CODE") ENABLE

--------------------------------------------------------
--  Ref Constraints for Table IBS_USER_PRODUCT_LINK
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_USER_PRODUCT_LINK" ADD FOREIGN KEY ("PRODUCT_CLASS")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_MASTER" ("CLASS") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_USER_PRODUCT_LINK" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "IBSUSER"."IBS_USER" ("ID") ENABLE

--------------------------------------------------------
--  Ref Constraints for Table IBS_UW_TRANSACTION
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_UW_TRANSACTION" ADD FOREIGN KEY ("QUOTE_SLIP_ID", "QUOTE_SLIP_VERSION")
	  REFERENCES "IBSUSER"."IBS_QUOTE_SLIP_HEADER" ("ID", "QUOTE_SLIP_VERSION") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_UW_TRANSACTION" ADD FOREIGN KEY ("PRODUCT_CLASS")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_MASTER" ("CLASS") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_UW_TRANSACTION" ADD FOREIGN KEY ("PRODUCT_UW_FIELD_ID")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_UW_FIELDS" ("ID") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_UW_TRANSACTION" ADD FOREIGN KEY ("STATUS_CODE")
	  REFERENCES "IBSUSER"."IBS_STATUS_MASTER" ("CODE") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table IBS_UW_TRANSACTION_HEADER
--------------------------------------------------------

  ALTER TABLE "IBSUSER"."IBS_UW_TRANSACTION_HEADER" ADD FOREIGN KEY ("QUOTE_ID")
	  REFERENCES "IBSUSER"."IBS_QUOTE_COMPARISION_HEADER" ("ID") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_UW_TRANSACTION_HEADER" ADD FOREIGN KEY ("QUOTE_SLIP_ID", "QUOTE_SLIP_VERSION")
	  REFERENCES "IBSUSER"."IBS_QUOTE_SLIP_HEADER" ("ID", "QUOTE_SLIP_VERSION") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_UW_TRANSACTION_HEADER" ADD FOREIGN KEY ("PRODUCT_CLASS")
	  REFERENCES "IBSUSER"."IBS_PRODUCT_MASTER" ("CLASS") ENABLE
 
  ALTER TABLE "IBSUSER"."IBS_UW_TRANSACTION_HEADER" ADD FOREIGN KEY ("STATUS_CODE")
	  REFERENCES "IBSUSER"."IBS_STATUS_MASTER" ("CODE") ENABLE
--------------------------------------------------------
--  DDL for Materialized View IBS_MAS_LOOKUP
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "IBSUSER"."IBS_MAS_LOOKUP"
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT 'STATUS' as  category,
  'ALL' as Level_1,
  'ALL' as Level_2,
   to_char(code) as code,
   description as description
  FROM IBS_STATUS_MASTER
  UNION ALL
  SELECT 'USER' as category,
  'ALL' as Level_1,
  'ALL' as Level_2,
   LOGIN_NAME as code,
   description as description
   FROM IBS_USER
   UNION ALL
   SELECT 'ROLES' as category,
  'ALL' as Level_1,
  'ALL' as Level_2,
   NAME as code,
   description as description
   FROM IBS_ROLES
   UNION ALL
   SELECT 'COMPANY' as category,
   'ALL' as Level_1,
   'ALL' as Level_2,
    code as code,
    NAME as description
    FROM IBS_COMPANY
    UNION ALL
    SELECT 'COMPANYBRANCH' as category,
    'ALL' as Level_1,
   'ALL' as Level_2,
    COMPANY_CODE as code,
    NAME as description
    FROM IBS_COMPANY_BRANCH
    UNION ALL
    SELECT 'INSURANCECOMPANY' as category,
   'ALL' as Level_1,
   'ALL' as Level_2,
    CODE as code,
    NAME as description
    FROM IBS_INSURANCE_COMPANY
     UNION ALL
    SELECT 'INSURANCECOMPANYCONTACT' as category,
   'ALL' as Level_1,
   'ALL' as Level_2,
    COMPANY_CODE as code,
    COMPANY_NAME as description
    FROM IBS_INSURANCE_COMPANY_CONTACT
    UNION ALL
    SELECT 'PRODUCTMASTER' as category,
   'ALL' as Level_1,
   'ALL' as Level_2,
    NAME as code,
    SHORTNAME as description
    FROM IBS_PRODUCT_MASTER
    UNION ALL
    SELECT 'INSCOMPPRODUCTLINK' as category,
   'ALL' as Level_1,
   'ALL' as Level_2,
    COMPANY_CODE as code,
    'ALL' as description
    FROM IBS_INSURANCE_COMP_PROD_LINK
--------------------------------------------------------
--  DDL for View IBS_V_INSURED_SEARCH
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "IBSUSER"."IBS_V_INSURED_SEARCH" ("CUST_ID", "CUST_NAME", "EMAIL", "MOB_NO", "INSURED_NAME", "ENQUIRY_NO", "QUOTATION_NO", "POLICY_NO", "CUST_CONTACT_ID", "INSURED_ID") AS 
  select X.CID AS CUST_ID, X.CNAME AS CUST_NAME, Z.primary_email_id AS EMAIL, z.primary_mobile_no MOB_NO, X.INAME AS INSURED_NAME, X. ENO AS ENQUIRY_NO, X.QID AS QUOTATION_NO, Y.PNUM AS POLICY_NO, X.C_CONTACTID AS CUST_CONTACT_ID,  X.IID AS INSURED_ID FROM
(select a.id as CID, a.contact_id as C_CONTACTID, a.name as CNAME, b.name as INAME, b.id as IID, c.enquiry_no as ENO, D.id as QID from
ibs_customer A, ibs_insured_master B, ibs_customer_enquiry C,
ibs_quote_slip_header D
where
a.id= b.customer_id and a.id = c.customer_id
and c.enquiry_no = d.enquiry_no (+)
) X,
(
select a.name as CNAME, b.name as INAME, c.enquiry_no as ENO, D.id as QID, e.policy_no as PNUM from
ibs_customer A, ibs_insured_master B, ibs_customer_enquiry C,
ibs_quote_slip_header D, ibs_uw_transaction_header E
where
a.id= b.customer_id and a.id = c.customer_id and a.id = D.customer_id and a.id = e.customer_id
and c.enquiry_no = d.enquiry_no and d.id = e.quote_slip_id and d.quote_slip_version = e.quote_slip_version
) Y, ibs_contact Z
 where X.QID = Y.QID (+) and X.C_CONTACTID = Z.ID
