REM INSERTING into IBS_CUSTOMER
Insert into IBS_CUSTOMER (ID,SALUTATION,NAME,CATEGORY,CUST_GROUP,CLASSIFICATION,SOURCE,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (1,'Mr','Shaik','Retail',null,null,null,1,null,null,null,null,null);
