REM INSERTING into IBS_PRODUCT_MASTER
Insert into IBS_PRODUCT_MASTER (CLASS,NAME,SHORTNAME,CATEGORISATION,STATUS,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (1,'Life INsurance','LI',null,'1',null,null,null,null);
Insert into IBS_PRODUCT_MASTER (CLASS,NAME,SHORTNAME,CATEGORISATION,STATUS,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (2,'Vehicle insurance','VI',null,'1',null,null,null,null);
Insert into IBS_PRODUCT_MASTER (CLASS,NAME,SHORTNAME,CATEGORISATION,STATUS,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (3,'Property Insurance','PI',null,'1',null,null,null,null);
