REM INSERTING into IBS_INSURED_MASTER
Insert into IBS_INSURED_MASTER (ID,CUSTOMER_ID,SALUTATION,NAME,SOURCE,ADDRESS,EMAIL,ALTERNATE_EMAIL,CONTACT_ID,SALES_EXECUTIVE,REC_CRE_USER_ID,REC_CRE_DATE,REC_UPD_USER_ID,REC_UPD_DATE) values (1,1,null,'insured',null,null,'abc@gmail.com',null,null,null,null,null,null,null);
