create table IBS_CONTACT(ID int,FIRST_NAME VARCHAR2(50),MIDDLE_NAME VARCHAR2(50),LAST_NAME VARCHAR2(50),TITLE VARCHAR2(3),PRIMARY_EMAIL_ID VARCHAR2(50),PRIMARY_MOBILE_NO VARCHAR2(20),
PRIMARY_LANDLINE_NO VARCHAR2(25),FAXNO VARCHAR2(25),CITY VARCHAR2(30),COUNTRY VARCHAR2(30),ADDRESS VARCHAR2(100),POBOX VARCHAR2(10),LOCATION_LATTITUDE NUMBER(5),
LOCATION_LONGITUDE NUMBER(5),ALTERNATE_EMAIL_ID_1 VARCHAR2(50),ALTERNATE_MOBILE_NO_1 VARCHAR2(20),ALTERNATE_LANDLINE_NO_1 VARCHAR2(25),ALTERNATE_EMAIL_ID_2 VARCHAR2(50),
ALTERNATE_MOBILE_NO_2 VARCHAR2(20),ALTERNATE_LANDLINE_NO_2 VARCHAR2(25),RECORD_TYPE NUMBER(2),IS_STATUS_ACTIVE VARCHAR2(1),REC_CRE_USER_ID int,
REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,PRIMARY KEY (ID));


create table IBS_COMPANY(CODE VARCHAR2(10),SHORTNAME VARCHAR2(10),NAME VARCHAR2(10),CONTACT_ID int,STATUS VARCHAR2(1),REC_CRE_USER_ID int,
REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,PRIMARY KEY (CODE),FOREIGN KEY (CONTACT_ID) REFERENCES IBS_CONTACT(ID));

create table IBS_COMPANY_BRANCH(CODE VARCHAR2(10),SHORTNAME VARCHAR2(10),COMPANY_CODE VARCHAR2(10),NAME VARCHAR2(30),ABBR VARCHAR2(4),CONTACT_ID NUMBER(25)
,STATUS VARCHAR2(1),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,PRIMARY KEY (CODE),FOREIGN KEY (COMPANY_CODE) REFERENCES IBS_COMPANY(CODE),
FOREIGN KEY (CONTACT_ID) REFERENCES IBS_CONTACT(ID));

create table IBS_INSURANCE_COMPANY(CODE VARCHAR2(10),SHORTNAME VARCHAR2(10),NAME VARCHAR2(10),CONTACT_ID NUMBER(25),
STATUS VARCHAR2(1),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,PRIMARY KEY (CODE),FOREIGN KEY (CONTACT_ID) REFERENCES IBS_CONTACT(ID));

create table IBS_PRODUCT_MASTER(CLASS int,NAME VARCHAR2(30),SHORTNAME VARCHAR2(15),CATEGORISATION VARCHAR2(15),STATUS VARCHAR2(1),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,PRIMARY KEY (CLASS));

create table IBS_INSURANCE_COMPANY_CONTACT(ID int,COMPANY_CODE VARCHAR2(10),COMPANY_NAME VARCHAR2(50),PRODUCT_CLASS int,CONTACT_ID NUMBER(25),STATUS VARCHAR2(1),
REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,PRIMARY KEY (ID),FOREIGN KEY (COMPANY_CODE) REFERENCES IBS_COMPANY(CODE),
FOREIGN KEY (PRODUCT_CLASS) REFERENCES IBS_PRODUCT_MASTER(CLASS),FOREIGN KEY (CONTACT_ID) REFERENCES IBS_CONTACT(ID));

create table IBS_PRODUCT_UW_FIELDS(ID int,PRODUCT_CLASS int,SRL_NO int,FIELD_NAME VARCHAR2(30),FIELD_TYPE VARCHAR2(30),IS_MANDATORY VARCHAR2(1),FIELD_LENGTH int,STATUS VARCHAR2(1),
SOURCE_OF_DATA VARCHAR2(25),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,PRIMARY KEY (ID),FOREIGN KEY (PRODUCT_CLASS) REFERENCES IBS_PRODUCT_MASTER(CLASS));


create table IBS_USER(ID int,LOGIN_NAME VARCHAR2(10),PASSWORD VARCHAR2(10),DESCRIPTION VARCHAR2(45),NAME VARCHAR2(100),CONTACT_NO VARCHAR2(20),EMAIL_ID VARCHAR2(50),BRANCH_CODE int,FREEZE_FLAG 
VARCHAR2(1),STATUS VARCHAR2(1),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,primary key(ID));


create table IBS_USER_PRODUCT_LINK(ID int,USER_ID int,PRODUCT_CLASS int,STATUS VARCHAR2(1),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,
REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,PRIMARY KEY (ID),FOREIGN KEY (PRODUCT_CLASS) REFERENCES IBS_PRODUCT_MASTER(CLASS),FOREIGN KEY (USER_ID) REFERENCES IBS_USER(ID));


create table IBS_USER_ROLE_LINK(ID int,USER_ID int,ROLE_ID int,STATUS VARCHAR2(1),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,primary key(ID));

create table IBS_INSURANCE_COMP_PROD_LINK(ID int,PRODUCT_CLASS int,COMPANY_CODE VARCHAR2(10),STATUS VARCHAR2(1),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,PRIMARY KEY (ID),FOREIGN KEY (PRODUCT_CLASS) REFERENCES IBS_PRODUCT_MASTER(CLASS));


create table IBS_CUSTOMER(ID int,SALUTATION VARCHAR2(5),NAME VARCHAR2(100),CATEGORY VARCHAR2(15),CUST_GROUP VARCHAR2(50),
CLASSIFICATION VARCHAR2(15),SOURCE VARCHAR2(15),CONTACT_ID NUMBER(25),SALES_EXECUTIVE VARCHAR2(50),
REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,PRIMARY KEY (ID),
FOREIGN KEY (CONTACT_ID) REFERENCES IBS_CONTACT(ID));

create table IBS_INSURED_MASTER(ID int,CUSTOMER_ID int,SALUTATION VARCHAR2(5),NAME VARCHAR2(100),SOURCE VARCHAR2(15),ADDRESS VARCHAR2(200),EMAIL VARCHAR2(45),ALTERNATE_EMAIL VARCHAR2(45),
CONTACT_ID NUMBER(25),SALES_EXECUTIVE VARCHAR2(50),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,PRIMARY KEY (ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES IBS_CUSTOMER(ID),FOREIGN KEY (CONTACT_ID) REFERENCES IBS_CONTACT(ID));

create table IBS_CUSTOMER_ENQUIRY(ENQUIRY_NO int,CUSTOMER_ID int,TYPE VARCHAR2(15),RECEIVED_DATE Timestamp,RCVD_FROM VARCHAR2(50),RCVD_EMAILID VARCHAR2(50),
RCVD_CONTACTNO VARCHAR2(50),PRODUCT_CLASS int,ENQUIRY_DESCRIPTION VARCHAR2(500),ENQUIRY_SUBJECTMATTER_EXPERT VARCHAR2(50),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,PRIMARY KEY (ENQUIRY_NO),FOREIGN KEY (CUSTOMER_ID) REFERENCES IBS_CUSTOMER(ID),
FOREIGN KEY (PRODUCT_CLASS) REFERENCES IBS_PRODUCT_MASTER(CLASS));


create table IBS_STATUS_MASTER(CODE int,DESCRIPTION varchar2(25),primary key(CODE));

create table IBS_QUOTE_SLIP_HEADER(ID int,ENQUIRY_NO int,QUOTE_SLIP_VERSION int,QUOTE_SLIP_DATE timestamp,PRODUCT_CLASS int,SUB_CLASS VARCHAR2(50),
CUSTOMER_ID int,INSURED_ID int,INSURED_NAME VARCHAR2(50),CONTRACT_PERIOD_FROM timestamp,CONTRACT_PERIOD_TO timestamp,POLICY_START_DATE timestamp,
POLICY_EXPIRY_DATE timestamp,QUOTE_SLIP_EMAILED VARCHAR2(1),REMARKS VARCHAR2(200),
STATUS_CODE int,REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,PRIMARY KEY (ID,QUOTE_SLIP_VERSION),FOREIGN KEY (PRODUCT_CLASS) REFERENCES IBS_PRODUCT_MASTER(CLASS)
,FOREIGN KEY (STATUS_CODE) REFERENCES IBS_STATUS_MASTER(CODE));

create table IBS_QUOTE_SLIP_DETAIL(ID int,QUOTE_SLIP_ID int,ENQUIRY_NO int,QUOTE_SLIP_VERSION int,QUOTE_SLIP_DATE timestamp,
ENQUIRY_COMPANY_CODE VARCHAR2(10),PRODUCT_CLASS int,PRODUCT_UW_FIELD_ID int,PRODUCT_UW_FIELD_ANSWER VARCHAR2(200),
CONTRACT_PERIOD_FROM timestamp,CONTRACT_PERIOD_TO timestamp,QUOTE_SLIP_EMAILED VARCHAR2(1),STATUS_CODE int,REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,
PRIMARY KEY (ID),FOREIGN KEY (QUOTE_SLIP_ID,QUOTE_SLIP_VERSION) REFERENCES IBS_QUOTE_SLIP_HEADER(ID,QUOTE_SLIP_VERSION),
FOREIGN KEY (PRODUCT_CLASS) REFERENCES IBS_PRODUCT_MASTER(CLASS),FOREIGN KEY (PRODUCT_UW_FIELD_ID) REFERENCES IBS_PRODUCT_UW_FIELDS(ID),FOREIGN KEY (STATUS_CODE) REFERENCES IBS_STATUS_MASTER(CODE));

create table IBS_QUOTE_COMPARISION_HEADER(ID int,QUOTE_SLIP_ID int,QUOTE_SLIP_VERSION int,ENQUIRY_NO int,PRODUCT_CLASS int,
SUB_CLASS VARCHAR2(50),CUSTOMER_ID int,INSURED_ID int,INSURED_NAME VARCHAR2(50),POLICY_START_DATE timestamp,POLICY_EXPIRY_DATE timestamp,RECOMMENDATION_SUMMARY VARCHAR2(1000),
QUOTE_RECOMMENDED VARCHAR2(1),STATUS_CODE int,REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,
PRIMARY KEY(ID),FOREIGN KEY (QUOTE_SLIP_ID,QUOTE_SLIP_VERSION) REFERENCES IBS_QUOTE_SLIP_HEADER(ID,QUOTE_SLIP_VERSION),FOREIGN KEY (PRODUCT_CLASS) REFERENCES IBS_PRODUCT_MASTER(CLASS),
FOREIGN KEY (STATUS_CODE) REFERENCES IBS_STATUS_MASTER(CODE));

create table IBS_QUOTE_COMPARISION_DETAIL(ID int,QUOTE_SLIP_ID int,QUOTE_SLIP_VERSION int,ENQUIRY_NO int,ENQUIRY_TYPE VARCHAR2(15),
QUOTED_COMPANY_CODE VARCHAR2(10),POLICY_START_DATE timestamp,POLICY_EXPIRY_DATE timestamp,PRODUCT_CLASS int,PRODUCT_UW_FIELD_ID int,
PRODUCT_UW_FIELD_ANSWER VARCHAR2(100),QUOTE_NO VARCHAR2(50),QUOTED_PREMIUM number(15,3),DISCOUNT_PERCENTAGE int,LOADING_PERCENTAGE int,
TOTAL_PREMIUM number(15,3),COMMISSION_ON_PRM number(15,3),POLICY_NO VARCHAR2(50),SUM_INSURED int,POLICY_TERM NUMBER(20,3),COVER_DESCRIPTION VARCHAR2(1000),
QUOTE_DATE timestamp,QUOTE_APPROVED_BY VARCHAR2(10),QUOTE_RECOMMENDED VARCHAR2(1),CLOSING_SLIP_EMAILED VARCHAR2(1),QUOTE_CONVERTED_TO_POL VARCHAR2(1),
STATUS_CODE int,REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,primary key(ID),
FOREIGN KEY (QUOTE_SLIP_ID,QUOTE_SLIP_VERSION) REFERENCES IBS_QUOTE_SLIP_HEADER(ID,QUOTE_SLIP_VERSION),
FOREIGN KEY (PRODUCT_CLASS) REFERENCES IBS_PRODUCT_MASTER(CLASS),FOREIGN KEY (PRODUCT_UW_FIELD_ID) REFERENCES IBS_PRODUCT_UW_FIELDS(ID),FOREIGN KEY (STATUS_CODE) REFERENCES IBS_STATUS_MASTER(CODE));

create table IBS_UW_TRANSACTION(QUOTE_SLIP_ID NUMBER(20),ENQUIRY_NO NUMBER(20),QUOTE_SLIP_VERSION NUMBER(3),QUOTE_SLIP_DATE timestamp,ENQUIRY_COMPANY_CODE VARCHAR2(10),
PRODUCT_CLASS NUMBER(10),PRODUCT_UW_FIELD_ID NUMBER(3),PRODUCT_UW_FIELD_ANSWER VARCHAR2(200),CONTRACT_PERIOD_FROM timestamp,CONTRACT_PERIOD_TO timestamp,
TYPE VARCHAR2(15),POLICY_NO VARCHAR2(50),STATUS_CODE NUMBER(2),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,
FOREIGN KEY (QUOTE_SLIP_ID,QUOTE_SLIP_VERSION) REFERENCES IBS_QUOTE_SLIP_HEADER(ID,QUOTE_SLIP_VERSION),FOREIGN KEY (PRODUCT_CLASS) REFERENCES IBS_PRODUCT_MASTER(CLASS),
FOREIGN KEY (PRODUCT_UW_FIELD_ID) REFERENCES IBS_PRODUCT_UW_FIELDS(ID),FOREIGN KEY (STATUS_CODE) REFERENCES IBS_STATUS_MASTER(CODE));

create table IBS_DOCUMENT_TABLE(ID int,ENQUIRY_NO int,ENQUIRY_TYPE VARCHAR2(20),DOC_SLIP_ID int,DOC_SLIP_VERSION int,DOC_RECIEVED_DESC VARCHAR2(500),
DOCUMENT BLOB,DOCUMENT_TYPE VARCHAR2(50),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,primary key(ID));

create table IBS_TASK(ID int,ENQUIRY_NO int,DOCUMENT_ID VARCHAR2(50),REFERRAL_DESC VARCHAR2(1000),STATUS_CODE NUMBER(2),
ASSIGNOR_USER_ID NUMBER(10),ASSIGNEE_USER_ID NUMBER(10),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,primary key(ID),
FOREIGN KEY (STATUS_CODE) REFERENCES IBS_STATUS_MASTER(CODE));

create table IBS_ROLES(ID int,NAME VARCHAR2(30) NOT NULL UNIQUE,DESCRIPTION VARCHAR2(100),STATUS VARCHAR2(1),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,primary key(ID));

create table IBS_ROLES_PRODUCT_PRIVILEGES(ID int,ROLE_ID int,ROLE_NAME VARCHAR2(30),PRODUCT_CLASS int,PRODUCT_NAME VARCHAR2(30),
FROM_SI_LIMIT NUMBER(13,3),TO_SI_LIMIT NUMBER(13,3),EMAIL_REQUISITION VARCHAR2(1),GENERATE_CLOSINGSLIP VARCHAR2(1),
EMAIL_CLOSINGSLIP VARCHAR2(1),GENERATE_QUOTESLIP VARCHAR2(1),EMAIL_QUOTESLIP VARCHAR2(1),FREETEXT1 VARCHAR2(100),FREETEXT2 VARCHAR2(100),
STATUS VARCHAR2(1),REMARKS VARCHAR2(50),REC_CRE_USER_ID int,REC_CRE_DATE Timestamp,REC_UPD_USER_ID int,REC_UPD_DATE Timestamp,primary key(ID),
FOREIGN KEY (ROLE_ID) REFERENCES IBS_ROLES(ID),FOREIGN KEY (ROLE_NAME) REFERENCES IBS_ROLES(NAME),
FOREIGN KEY (PRODUCT_CLASS) REFERENCES IBS_PRODUCT_MASTER(CLASS));

create table IBS_RECORD_TYPES(TYPE NUMBER(2),DESCRIPTION VARCHAR2(25));





