CREATE USER IBSUser identified by oracle;

grant create session to IBSUser;

GRANT CREATE TABLE to IBSUser;

GRANT CREATE VIEW to IBSUser;

GRANT CREATE ANY MATERIALIZED VIEW TO IBSUser;

GRANT UNLIMITED TABLESPACE TO IBSUser;